version: '3'
services:  
  electricityoverflowusageapi:	
    build: .	
    ports: 	 
    - "8080:80"	 
    - "8081:443"	
    environment:	  
      ASPNETCORE_URLS: "https://+;http://+"	  
      ASPNETCORE_HTTPS_PORT: "8081"	  
      ASPNETCORE_ENVIRONMENT: "Development"	
    volumes:	 
    - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets	 
    - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/